media:
  input: src/assets
  output: src/assets

content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc