media:
  input: src/assets
  output: src/assets

content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, pubDatetime, modDatetime ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Published at, type: date }
      - { name: modDatetime, label: Modified at, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: OG image, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }