content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    view:
      fields: [ tags ]
    fields:
      - name: tags
        type: text
        label: Tags
        list: true